name: Deploy to Firebase Hosting (live)

on:
  push:
    branches: [ main ]    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODE_SKILLS_SURVEY }}'
          channelId: live
          projectId: code-skills-survey
